import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/share/Header"
import Footer from "@/components/share/Footer"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header/>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
